server:
    port: 8080
    contextPath: /client

security:
    basic:
        enabled: false

config:
    oauth2:
        clientID: trusted
        clientSecret: secret
        accessTokenUri: http://localhost:8081/oauth/token
        userAuthorizationUri: http://localhost:8081/oauth/authorize
        resourceURI: http://localhost:8082/api/
        messageURI: http://localhost:8082/api/private/messages
        publicMessageURI: http://localhost:8082/api/public/messages